# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_activity_facebook_rest_root:
    type:     rest
    prefix:   /
    resource: CampaignChain\Activity\FacebookBundle\Controller\REST\ActivityController