# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_activity_facebook_publish_status_new:
    pattern:  /activity/facebook/publish-status/new
    defaults: { _controller: campaignchain.activity.controller.facebook.publish_status:newAction }

campaignchain_activity_facebook_publish_status_edit:
    pattern:  /activity/facebook/publish-status/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.facebook.publish_status:editAction }

campaignchain_activity_facebook_publish_status_edit_modal:
    pattern:  /modal/activity/facebook/publish-status/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.facebook.publish_status:editModalAction }

campaignchain_activity_facebook_publish_status_edit_api:
    pattern:  /api/private/activity/facebook/publish-status/byactivity/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.facebook.publish_status:editApiAction }
    options:
        expose: true

campaignchain_activity_facebook_publish_status_read:
    pattern:  /activity/facebook/publish-status/{id}
    defaults: { _controller: campaignchain.activity.controller.facebook.publish_status:readAction }